### ISSUE TITLE
salt '*' state.highstate fails with current salt ver. 2017.7.2

### ISSUE THREAD

**Issue by TheBigBear** [vishal-biyani/saltstack-cluster#3]
Thank you so much for this nice mini cluster setup. 

But something seems to be broken with current version of salt --version 2017.7.2 ?

When I run ``` sudo salt '*' state.highstate ```

```
sudo salt '*' state.highstate
smaster.learn.com:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found.
     Changes:   

Summary for smaster.learn.com
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
1.sagent.learn.com:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found.
     Changes:   

Summary for 1.sagent.learn.com
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
0.sagent.learn.com:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found.
     Changes:   

Summary for 0.sagent.learn.com
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
```

Also the ``` /vagrant/salt/srv/salt/top.sls ``` file contains:
```
base:
  'G@roles:apache':
    - apache
  'G@roles:redis':
    - redis.server
```

But a ``` sudo salt '*' state.show_top ``` shows empty or non-exixstent top file?
```
sudo salt '*' state.show_top
0.sagent.learn.com:
    ----------
1.sagent.learn.com:
    ----------
smaster.learn.com:
    ----------
```
Which explains why the  ``` highstate ``` fails? But I don't know why it doesn't find and run the highstate under this version? Is this a salt version regression?

The active salt master config file is:
``` sudo cat -tve /etc/salt/master | egrep -v '^#|^\$' ```
```
 file_roots:$
   base:$
     - /srv/salt$
     - /vagrant/salt/srv/salt$
 pillar_roots:$
   base:$
     - /srv/pillar$
     - /vagrant/salt/srv/pillar$
```

all the required (and un-edited) files from your git repo are there ``` ls -R /vagrant/salt/srv/salt/ ```
```
/vagrant/salt/srv/salt/:
apache  orch  redis  redis_key_check.sls  top.sls

/vagrant/salt/srv/salt/apache:
apache_down.sls  files  init.sls

/vagrant/salt/srv/salt/apache/files:
index.html.jinja

/vagrant/salt/srv/salt/orch:
flow1.sls

/vagrant/salt/srv/salt/redis:
common.sls  files  init.sls  map.jinja  server.sls

/vagrant/salt/srv/salt/redis/files:
redis-2.4.conf.jinja  redis-2.8.conf.jinja  redis-3.2.conf.jinja  upstart.conf.jinja
redis-2.6.conf.jinja  redis-3.0.conf.jinja  redis_initd.jinja
```

And I had added the ``` apache ``` role grain

``` sudo salt '*' cmd.run 'cat /etc/salt/grains' ```
```
1.sagent.learn.com:
    role:
    - apache
0.sagent.learn.com:
    role:
    - apache
smaster.learn.com:
    role:
    - apache
```

Any idea what is going on here?

**Comment by vishal-biyani** [comment]
Hi @TheBigBear Thanks for filing an issue. I think since I was still working on this tutorial, somewhere a small typo has caused the issue. The grain I am using is `roles` (Plural with a S)

```
cat top.sls 
base:
  'G@roles:apache':
    - apache
```

After I assigned grain `roles` a value of `apache`, it is showing up in `show_top`

Can you please verify if same is the issue in your setup too?

**Comment by TheBigBear** [comment]
@vishal-biyani thank you so much! I just didn't spot that small difference. Yes, it makes all the difference. That solved it for me. 

I am very much looking forward to reading your upcoming step by step guide to salt formulas and maybe you will even go into how to use pillars to over-ride default salt-formula settings when installing using any formula from the default public salt formulas repo. A topic which saltstack are not covering in any easy to understand way as far as I can find.
